/*
 * This source file was generated by the Gradle 'init' task
 */
package org.soft2412.vsas;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

class AppTest {
  @Test
  public void testAppExists() {
    // Test that App class can be instantiated
    App app = new App();
    assertNotNull(app);
  }
}
