/*
 * This source file was generated by the Gradle 'init' task
 */
package org.soft2412.vsas;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

}
