/*
 * This source file was generated by the Gradle 'init' task
 */
package org.soft2412.vsas;

import org.soft2412.vsas.cli.CommandDispatcher;

public final class App {
  public static void main(String[] args) {
    int code = new CommandDispatcher().dispatch(args);
    System.exit(code);
  }
}
